version: '3.1'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "sail"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: 'testing'
    volumes:
      - './volume:/docker-entrypoint-initdb.d/'